
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvpod
  template:
    metadata:
      labels:
        app: pvpod
    spec:
      containers:
      - name: test
        image: nginx
        volumeMounts:
        - mountPath: "/tmp/vol"
          name: myvol
      volumes:
      - name: myvol
        persistentVolumeClaim:
          claimName: mypvc

